// latest versions
const pentaho = "0.6.0";

export const alignmentData: Record<string, { pentaho: string }> = {
  Accordion: { pentaho },
  ActionBar: { pentaho },
  AppSwitcher: { pentaho },
  Avatar: { pentaho },
  AvatarGroup: { pentaho },
  Badge: { pentaho },
  Banner: { pentaho },
  BreadCrumb: { pentaho },
  BulkActions: { pentaho },
  Button: { pentaho },
  Card: { pentaho },
  Checkbox: { pentaho },
  CheckboxGroup: { pentaho },
  CodeEditor: { pentaho },
  ColorPicker: { pentaho },
  Container: { pentaho },
  DatePicker: { pentaho },
  Dialog: { pentaho },
  DotPagination: { pentaho },
  Drawer: { pentaho },
  Dropdown: { pentaho },
  DropDownMenu: { pentaho },
  EmptyState: { pentaho },
  FileUploader: { pentaho },
  FilterGroup: { pentaho },
  Footer: { pentaho },
  GlobalActions: { pentaho },
  Header: { pentaho },
  Input: { pentaho },
  Loading: { pentaho },
  MultiButton: { pentaho },
  NumberInput: { pentaho },
  Pagination: { pentaho },
  ProgressBar: { pentaho },
  Radio: { pentaho },
  RadioGroup: { pentaho },
  SearchInput: { pentaho },
  Section: { pentaho },
  Select: { pentaho },
  Skeleton: { pentaho },
  Slider: { pentaho },
  Snackbar: { pentaho },
  Switch: { pentaho },
  // Table: { pentaho },
  Tabs: { pentaho },
  Tag: { pentaho },
  TagsInput: { pentaho },
  TextArea: { pentaho },
  TimePicker: { pentaho },
  ToggleButton: { pentaho },
  Tooltip: { pentaho },
  Typography: { pentaho },
  VerticalNavigation: { pentaho },
};
