// latest versions
const next = "5.9.5";
const pentaho = "0.6.0";

export const alignmentData: Record<string, { next: string; pentaho: string }> =
  {
    Accordion: { next, pentaho },
    ActionBar: { next, pentaho },
    AppSwitcher: { next, pentaho },
    Avatar: { next, pentaho },
    AvatarGroup: { next, pentaho },
    Badge: { next, pentaho },
    Banner: { next, pentaho },
    BreadCrumb: { next, pentaho },
    BulkActions: { next, pentaho },
    Button: { next, pentaho },
    Card: { next, pentaho },
    Carousel: { next, pentaho },
    Checkbox: { next, pentaho },
    CheckboxGroup: { next, pentaho },
    CodeEditor: { next, pentaho },
    ColorPicker: { next, pentaho },
    Container: { next, pentaho },
    DatePicker: { next, pentaho },
    Dialog: { next, pentaho },
    DotPagination: { next, pentaho },
    Drawer: { next, pentaho },
    Dropdown: { next, pentaho },
    DropDownMenu: { next, pentaho },
    EmptyState: { next, pentaho },
    FileUploader: { next, pentaho },
    FilterGroup: { next, pentaho },
    Footer: { next, pentaho },
    GlobalActions: { next, pentaho },
    Header: { next, pentaho },
    Input: { next, pentaho },
    Loading: { next: "5.9.3", pentaho },
    MultiButton: { next, pentaho },
    NumberInput: { next, pentaho },
    Pagination: { next, pentaho },
    ProgressBar: { next: "5.9.3", pentaho },
    Radio: { next, pentaho },
    RadioGroup: { next, pentaho },
    ScrollToHorizontal: { next, pentaho },
    ScrollToVertical: { next, pentaho },
    SearchInput: { next, pentaho },
    Section: { next, pentaho },
    Select: { next, pentaho },
    Skeleton: { next, pentaho },
    Slider: { next: "5.9.3", pentaho },
    Snackbar: { next, pentaho },
    Switch: { next, pentaho },
    // Table: {  next, pentaho },
    Tabs: { next, pentaho },
    Tag: { next, pentaho },
    TagsInput: { next, pentaho },
    TextArea: { next, pentaho },
    TimePicker: { next, pentaho },
    ToggleButton: { next, pentaho },
    Tooltip: { next, pentaho },
    Typography: { next, pentaho },
    VerticalNavigation: { next: "5.9.3", pentaho },
  };
