export default [
  {
    moduleId: "react",
    bundle: "react.production.min.js",
    bundleSrc: "./esm-externals/react.production.min.js",
    virtualSrc: `import * as React from "react";
    export default React;

    export {
      Fragment,
      StrictMode,
      Profiler,
      Suspense,
      Children,
      Component,
      PureComponent,
      cloneElement,
      createContext,
      createElement,
      createFactory,
      createRef,
      forwardRef,
      isValidElement,
      lazy,
      memo,
      startTransition,
      useCallback,
      useContext,
      useDebugValue,
      useDeferredValue,
      useEffect,
      useId,
      useImperativeHandle,
      useInsertionEffect,
      useLayoutEffect,
      useMemo,
      useReducer,
      useRef,
      useState,
      useSyncExternalStore,
      useTransition,
      version,
    } from "react";`,
  },
  {
    moduleId: "react-dom",
    bundle: "react-dom.production.min.js",
    bundleSrc: "./esm-externals/react-dom.production.min.js",
    virtualSrc: `export {
      default,
      flushSync,
      createPortal,
      findDOMNode,
      hydrate,
      render,
      unmountComponentAtNode,
      unstable_batchedUpdates,
      unstable_renderSubtreeIntoContainer,
      version,
    } from "react-dom";`,
  },
  {
    moduleId: "react-router-dom",
    bundle: "react-router-dom.production.min.js",
    bundleSrc: "./esm-externals/react-router-dom.production.min.js",
    virtualSrc: `export * from "react-router-dom";`,
  },
  {
    moduleId: "@emotion/react",
    bundle: "emotion-react.production.min.js",
    bundleSrc: "./esm-externals/emotion-react.production.min.js",
    virtualSrc: `export * from "@emotion/react";`,
  },
  {
    moduleId: "@emotion/cache",
    bundle: "emotion-cache.production.min.js",
    bundleSrc: "./esm-externals/emotion-cache.production.min.js",
    virtualSrc: `import createCache from "@emotion/cache"; export default createCache;`,
  },
  {
    moduleId: "@pentaho/app-shell-shared",
    bundle: "app-shell-shared.esm.js",
    bundleSrc: "@pentaho/app-shell-shared/bundles/app-shell-shared.esm.js",
    virtualSrc: `export * from "@pentaho/app-shell-shared";`,
  },
  {
    moduleId: "@pentaho/app-shell-services",
    bundle: "app-shell-services.esm.js",
    bundleSrc: "@pentaho/app-shell-services/bundles/app-shell-services.esm.js",
    virtualSrc: `export { default } from "@pentaho/app-shell-services";
    export * from "@pentaho/app-shell-services";`,
  },
  {
    moduleId: "@pentaho/uikit-react-shared",
    bundle: "uikit-react-shared.esm.js",
    bundleSrc: "@pentaho/uikit-react-shared/bundles/uikit-react-shared.esm.js",
    virtualSrc: `export * from "@pentaho/uikit-react-shared";`,
  },
];
