import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";

import { loadMetadata } from "../utils/metadata.js";

/**
 * Generate lean AGENTS.md and update CLAUDE.md.
 * Phase 5.1b: Non-destructive initialization for agents.
 *
 * Creates:
 * - .claude/rules/hv-uikit.md (lean guide, ~12 KB)
 * - CLAUDE.md reference (if doesn't exist or needs update)
 */
export async function init(targetDir?: string): Promise<void> {
  const dir = targetDir ?? ".";
  try {
    const metadata = loadMetadata();

    // Create .claude/rules directory
    const rulesDir = join(dir, ".claude", "rules");
    mkdirSync(rulesDir, { recursive: true });

    // Generate and write lean AGENTS.md
    const agentsPath = join(rulesDir, "hv-uikit.md");
    const agentsContent = generateLeanAgentsMd(metadata);
    writeFileSync(agentsPath, agentsContent, "utf-8");

    // Create or update CLAUDE.md with reference
    const claudePath = join(dir, "CLAUDE.md");
    updateClaudeMd(claudePath);

    // eslint-disable-next-line no-console
    console.log(chalk.green(`✓ Generated HV UI Kit agent guide`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Rules: ${agentsPath}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Reference: ${claudePath}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Version: ${metadata.version}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Components: ${metadata.components.length}`));
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error(chalk.red(`✗ Failed to initialize agent guide: ${error}`));
    // eslint-disable-next-line no-process-exit
    process.exit(1);
  }
}

/**
 * Create or update CLAUDE.md with reference to hv-uikit rules.
 * Idempotent: checks if reference already exists before adding.
 */
function updateClaudeMd(claudePath: string): void {
  const rulesRef =
    "Read the HV UI Kit component guide:\n\n<file:.claude/rules/hv-uikit.md>\n\n";

  let content = "";
  try {
    content = readFileSync(claudePath, "utf-8");
  } catch {
    // File doesn't exist, we'll create it
  }

  // Check if reference already exists (idempotent)
  if (!content.includes(".claude/rules/hv-uikit.md")) {
    // Prepend reference
    const newContent = rulesRef + content;
    writeFileSync(claudePath, newContent, "utf-8");
  }
}

/**
 * Generate lean AGENTS.md content from component metadata.
 * Focus: Inventory + Universal Rules + MCP delegation
 * Size: ~12 KB (reasonable for context windows)
 */
function generateLeanAgentsMd(metadata: any): string {
  const { version, generatedAt, components } = metadata;

  // Group components by category based on naming patterns
  const categorized = categorizeComponents(components);
  const componentSections = Object.entries(categorized)
    .map(([category, comps]: [string, any[]]) => {
      const items = (comps as any[])
        .map((c) => `- **${c.displayName}** — ${c.purpose}`)
        .join("\n");
      return `### ${category}\n${items}`;
    })
    .join("\n\n");

  return `# HV UI Kit Agent Guide

> Auto-generated for @pentaho/uikit-react-core@${version}
> Generated: ${generatedAt}
> 
> **Do not edit this file.** Regenerated on \`npm install\` and version upgrades.

## Overview

This guide covers the HV UI Kit component library. Use this as your reference for:
- What components exist and their purpose
- Universal styling and accessibility rules
- When to query the MCP server for full contracts

For detailed component contracts (all variants, state rules, token constraints, anti-patterns, a11y), use the MCP server.

## Component Inventory

${componentSections}

## Universal Rules

### Tokens (Always Required)
- **Colors**: Use semantic tokens only
  - \`primary\`, \`secondary\`, \`positive\`, \`negative\`, \`warning\`
  - Never raw hex, rgb, or named colors
- **Spacing**: Use token values
  - \`xs\`, \`sm\`, \`md\`, \`lg\`, \`xl\`
  - Never raw pixel values or custom margins/padding
- **Typography**: Use HvTypography with semantic variants
  - \`display\`, \`headings\`, \`body\`, \`caption\`, \`label\`
  - Never inline font-size or font-weight

### Accessibility (Always Required)
- **Forms**: Every input must have a label or \`aria-label\`
  \`\`\`tsx
  <HvInput label="Name" />  // or
  <HvInput aria-label="Search" placeholder="Type..." />
  \`\`\`
- **Buttons**: Semantic variants should match intent
  \`\`\`tsx
  <HvButton variant="contained">Save</HvButton>    // primary action
  <HvButton variant="negative">Delete</HvButton>  // destructive
  <HvButton variant="ghost">Cancel</HvButton>     // secondary
  \`\`\`
- **Toggle buttons**: Must include \`aria-pressed\` when toggling state
  \`\`\`tsx
  <HvButton variant="ghost" selected={isActive} aria-pressed={isActive}>
    Bold
  </HvButton>
  \`\`\`
- **Images/Avatars**: Always include \`alt\` or \`aria-label\`
  \`\`\`tsx
  <HvAvatar src="user.jpg" alt="John Doe" />
  \`\`\`

## Critical Anti-Patterns (Avoid These)

1. **Raw values instead of tokens**
   - ❌ \`<HvButton style={{ color: "#FF0000", padding: "16px" }} />\`
   - ✅ \`<HvButton variant="negative" />\` (uses semantic tokens)

2. **Missing accessible names on interactive elements**
   - ❌ \`<HvInput />\` (no label or aria-label)
   - ✅ \`<HvInput label="Email" required />\`

3. **Using disabled without explaining why**
   - ❌ \`<HvButton disabled>Save</HvButton>\`
   - ✅ \`<HvButton disabled>Save</HvButton>\` + helper text explaining why disabled

## Getting Full Component Contracts

This guide covers universal rules only. For detailed information about a specific component:

\`\`\`bash
npx uikit-tools mcp get_component_contract --component HvButton
\`\`\`

Returns:
- All available variants and their semantic meaning
- State rules (when to use \`checked\`, \`disabled\`, \`selected\`, etc.)
- Token constraints (allowed color/size values)
- Anti-patterns specific to this component
- Accessibility requirements (ARIA attributes)
- Validation rules (what inputs are valid)

## Listing All Components

To see the full inventory programmatically:

\`\`\`bash
npx uikit-tools mcp list_components --limit 10 --offset 0
\`\`\`

## Validation

Before committing code, validate against the component contracts:

\`\`\`bash
npx uikit-tools validate src/**/*.tsx
\`\`\`

Checks:
- Invalid component variant values
- Raw color/spacing values instead of tokens
- Known anti-pattern usage
- Missing required props (esp. accessibility)

## Workflow

1. **Understand the task** — What are you building?
2. **Check this guide** — What components exist? What are universal rules?
3. **Query MCP if needed** — Get full contract for specific component
   \`\`\`bash
   npx uikit-tools mcp get_component_contract --component HvInput
   \`\`\`
4. **Generate or write code** — Follow the contract and universal rules
5. **Validate before committing**
   \`\`\`bash
   npx uikit-tools validate src/**/*.tsx
   \`\`\`
6. **Fix violations** — Review errors and correct (usually tokens or a11y)

## Example: Building a Form

\`\`\`tsx
import { HvInput, HvCheckBox, HvButton } from "@pentaho/uikit-react-core";

export function LoginForm() {
  return (
    <form>
      {/* Input with label (a11y requirement) */}
      <HvInput 
        label="Email" 
        type="email" 
        required
      />
      
      {/* Checkbox with label (a11y requirement) */}
      <HvCheckBox 
        label="Remember me" 
      />
      
      {/* Primary button for form submission */}
      <HvButton variant="contained" type="submit">
        Sign In
      </HvButton>
    </form>
  );
}
\`\`\`

Run validation:
\`\`\`bash
npx uikit-tools validate LoginForm.tsx
# ✓ All validations passed
\`\`\`

## Questions?

- **Need variants for a component?** → \`mcp get_component_contract\`
- **Want examples?** → See component Storybook stories
- **Validation failing?** → Check the error message, query MCP for full rules
- **Token values?** → Check design tokens documentation
`;
}

/**
 * Categorize components by functional group.
 */
function categorizeComponents(components: any[]): Record<string, any[]> {
  const categories: Record<string, any[]> = {
    "Input Components": [],
    "Selection Components": [],
    "Display Components": [],
    "Container Components": [],
    "Feedback Components": [],
    "Other Components": [],
  };

  components.forEach((c: any) => {
    const name = c.name;

    // Categorize based on naming patterns and purpose
    if (
      name.includes("Input") ||
      name.includes("Select") ||
      name.includes("DatePicker") ||
      name.includes("TimePicker") ||
      name.includes("ColorPicker") ||
      name.includes("TextArea") ||
      name.includes("TagsInput") ||
      name.includes("SearchInput")
    ) {
      categories["Input Components"].push(c);
    } else if (
      name.includes("CheckBox") ||
      name.includes("Radio") ||
      name.includes("Switch") ||
      name.includes("Toggle")
    ) {
      categories["Selection Components"].push(c);
    } else if (
      name.includes("Button") ||
      name.includes("Badge") ||
      name.includes("Avatar") ||
      name.includes("Tag") ||
      name.includes("Typography") ||
      name.includes("Icon") ||
      name.includes("Status")
    ) {
      categories["Display Components"].push(c);
    } else if (
      name.includes("Card") ||
      name.includes("Dialog") ||
      name.includes("Drawer") ||
      name.includes("Table") ||
      name.includes("List") ||
      name.includes("Accordion") ||
      name.includes("Panel") ||
      name.includes("TreeView") ||
      name.includes("Grid") ||
      name.includes("Section")
    ) {
      categories["Container Components"].push(c);
    } else if (
      name.includes("Snackbar") ||
      name.includes("Banner") ||
      name.includes("Tooltip") ||
      name.includes("Loading") ||
      name.includes("Progress") ||
      name.includes("EmptyState")
    ) {
      categories["Feedback Components"].push(c);
    } else {
      categories["Other Components"].push(c);
    }
  });

  // Filter out empty categories
  return Object.fromEntries(
    Object.entries(categories).filter(([, comps]) => comps.length > 0),
  );
}
