import { writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";

import { loadMetadata } from "../utils/metadata.js";

/**
 * Generate AGENTS.md in the target directory.
 * This is the primary instruction file for agents using HV UI Kit components.
 */
export async function init(targetDir?: string): Promise<void> {
  const dir = targetDir ?? ".";
  try {
    const metadata = loadMetadata();
    const outputPath = join(dir, "AGENTS.md");

    // Generate AGENTS.md content
    const content = generateAgentsMd(metadata);

    writeFileSync(outputPath, content, "utf-8");
    // eslint-disable-next-line no-console
    console.log(chalk.green(`✓ Generated AGENTS.md at ${outputPath}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Installed version: ${metadata.version}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Components: ${metadata.components.length}`));
    // eslint-disable-next-line no-console
    console.log(chalk.gray(`  Generated: ${metadata.generatedAt}`));
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error(chalk.red(`✗ Failed to generate AGENTS.md: ${error}`));
    // eslint-disable-next-line no-process-exit
    process.exit(1);
  }
}

/**
 * Generate the AGENTS.md content from component metadata.
 * Format follows the state-of-art pattern: compact router with progressive disclosure.
 */
function generateAgentsMd(metadata: any): string {
  const { version, generatedAt, components } = metadata;

  // Generate patterns for key components (HvButton, HvAvatar, and any with variantSemantics)
  const keyComponents = components.filter(
    (c: any) =>
      c.name === "HvButton" ||
      c.name === "HvAvatar" ||
      (c.variantSemantics && c.variantSemantics.length > 0),
  );
  const patternSections = keyComponents
    .slice(0, 2) // Limit to first 2 for now (HvButton, HvAvatar)
    .map((c: any) => generateComponentPatterns(c))
    .join("\n");

  const tokenRules = generateTokenRules(components);
  const componentList = components
    .map((c: any) => `- **${c.displayName}** (\`${c.name}\`): ${c.purpose}`)
    .join("\n");

  return `# HV UI Kit Agent Guide

> Auto-generated for @pentaho/uikit-react-core@${version}
> Generated: ${generatedAt}
> 
> **Do not edit this file.** It is regenerated on npm install and version upgrades.
> Add project-specific guidance in AGENTS.local.md instead.

## Quick Start

You have access to the HV UI Kit component library. This guide shows correct patterns and where to find detailed rules.

**Installed version:** \`${version}\`
**Components in this version:** ${components.length}

## Component Inventory

${componentList}

## Correct Patterns

Use these patterns as your starting point. When you need the full contract for a component (all variants, anti-patterns, accessibility rules), query the MCP server.

${patternSections}

## Token Rules

All styling must use design tokens. Do not use raw hex, rgb, or px values.

${tokenRules}

## Validation

After generating code, run validation to catch contract violations before review:

\`\`\`bash
npm run validate src/**/*.tsx
# or manually:
npx @pentaho/uikit-tools validate src/**/*.tsx
\`\`\`

Validation checks:
- Invalid component variants
- Raw color/spacing values instead of tokens
- Anti-pattern usage (e.g., misused \`selected\` prop)
- Missing accessibility conditions

If validation fails, review the message and either:
1. Correct the code directly (e.g., replace \`#FF0000\` with \`color="negative"\`)
2. Query the MCP server for the full contract: \`npx @pentaho/uikit-tools mcp\`

## Retrieval

For detailed component contracts, examples, and token rules beyond this guide:

\`\`\`bash
npx @pentaho/uikit-tools mcp
\`\`\`

This starts an MCP server with tools:
- \`list_components\` — full inventory
- \`get_component_contract\` — complete contract for any component
- \`get_component_examples\` — canonical examples per intent
- \`get_token_rules\` — allowed values per token category
- \`search\` — free-text search
- \`validate_usage\` — pre-flight validation on code snippets

## Design-to-Code

When building from a Figma design:

1. **Identify the component.** Figma's Code Connect shows the mapped component and variant intent.
2. **Check this guide.** Use the patterns here as your starting point.
3. **Query if needed.** If the guide doesn't cover your case, use MCP retrieval.
4. **Validate before committing.** Run validation to catch off-system usage before review.

## Anti-Patterns to Avoid

Each component has documented anti-patterns. Run:

\`\`\`bash
npx @pentaho/uikit-tools mcp
\`\`\`

Then use the \`get_component_contract\` tool to see all known misuse cases and their corrections.

## Questions?

This file points at the real metadata. If something is unclear:
- Check the component's full contract via MCP
- Look at the component's Storybook stories for examples
- Review Button.tsx JSDoc in the repo (@variantSemantics, @antiPatterns, etc.)
`;
}

/**
 * Generate usage patterns for a component based on its contract.
 */
function generateComponentPatterns(component: any): string {
  let patterns = `### ${component.name} Patterns\n\n`;

  if (component.variantSemantics && component.variantSemantics.length > 0) {
    patterns += `**Variants (by semantic meaning):**\n\n`;
    component.variantSemantics.forEach((v: any) => {
      patterns += `- \`${v.name}\`: ${v.semanticMeaning || v.description}\n`;
    });
    patterns += `\n`;
  }

  // Generate appropriate example usage based on component
  if (component.name === "HvButton") {
    patterns += `**Correct usage:**\n\n`;
    patterns += `\`\`\`tsx
// Primary CTA
<HvButton variant="contained">Save</HvButton>

// Secondary action
<HvButton variant="subtle">Cancel</HvButton>

// Destructive action (requires aria-label for a11y)
<HvButton variant="negative" aria-label="Delete item">Delete</HvButton>

// Toggle button (implies aria-pressed)
<HvButton 
  variant="ghost" 
  selected={isActive} 
  aria-pressed={isActive}
  aria-label="Toggle view"
>
  View
</HvButton>
\`\`\`\n\n`;
  } else if (component.name === "HvAvatar") {
    patterns += `**Correct usage:**\n\n`;
    patterns += `\`\`\`tsx
// User profile avatar with image
<HvAvatar src="profile.jpg" alt="User Name" />

// Avatar with initials fallback
<HvAvatar variant="circular">JD</HvAvatar>

// Avatar with status indicator
<HvAvatar src="user.jpg" status="online" />

// Logo avatar (square variant)
<HvAvatar variant="square" src="logo.png" />

// In avatar group (let group control styling)
<HvAvatarGroup>
  <HvAvatar src="user1.jpg" alt="User 1" />
  <HvAvatar src="user2.jpg" alt="User 2" />
  <HvAvatar src="user3.jpg" alt="User 3" />
</HvAvatarGroup>
\`\`\`\n\n`;
  } else {
    patterns += `**Correct usage:**\n\n`;
    patterns += `\`\`\`tsx
// Use semantic variants for proper accessibility and visual hierarchy
<${component.name} variant="default" />
\`\`\`\n\n`;
  }

  if (component.antiPatterns && component.antiPatterns.length > 0) {
    patterns += `**Anti-patterns (avoid these):**\n\n`;
    component.antiPatterns.slice(0, 3).forEach((ap: any) => {
      patterns += `- ❌ ${ap.pattern} — ${ap.why}\n`;
      patterns += `  ✓ Instead: ${ap.correct}\n\n`;
    });
  }

  return patterns;
}

/**
 * Generate token rules section from components' token constraints.
 */
function generateTokenRules(components: any[]): string {
  const constraints = new Map<string, Set<string>>();

  components.forEach((c: any) => {
    if (c.tokenConstraints) {
      c.tokenConstraints.forEach((tc: any) => {
        if (!constraints.has(tc.category)) {
          constraints.set(tc.category, new Set());
        }
        if (tc.allowedValues) {
          tc.allowedValues.forEach((v: string) => {
            constraints.get(tc.category)!.add(v);
          });
        }
      });
    }
  });

  let rules = "";
  constraints.forEach((values, category) => {
    rules += `**${category}:** Use tokens only. Allowed: ${Array.from(values).join(", ") || "component-specific"}\n\n`;
  });

  if (!rules) {
    rules =
      "**Color:** Use semantic tokens (primary, secondary, positive, negative, warning, inherit)\n\n**Spacing:** Use token values (never raw px)\n\n";
  }

  return rules;
}
