import chalk from "chalk";
import { Command } from "commander";
import fs from "fs-extra";

import { __dirname } from "./utils.js";

const DESCRIPTIONS = `${__dirname}/descriptions`;

/** Marks the block this command owns, so re-running replaces it rather than duplicating. */
const START = "<!-- uikit-cli:start -->";
const END = "<!-- uikit-cli:end -->";

const pkgVersion = () =>
  fs.readJsonSync(`${__dirname}/../package.json`, { throws: false })?.version ??
  "unknown";

const readIndex = () =>
  fs.readJsonSync(`${DESCRIPTIONS}/index.json`, { throws: false });

/**
 * Bundle every component description at build-time density.
 *
 * Bundling rather than looking up on demand is deliberate: the result is pinned
 * to the version of the UI Kit this CLI came from, so a product on an older
 * major cannot be told about components it does not have.
 */
function buildContext(index) {
  const parts = index.map((entry) =>
    fs
      .readFileSync(
        `${DESCRIPTIONS}/${entry.file.replace(/\.md$/, ".dense.md")}`,
        "utf-8",
      )
      .trim(),
  );
  return [
    `<!-- Generated by \`uikit-cli init --agents\` from @pentaho/uikit-cli@${pkgVersion()}.`,
    `     Re-run after upgrading the UI Kit. Do not edit by hand. -->`,
    "",
    "# UI Kit components",
    "",
    `${index.length} components, ${index.filter((e) => e.hasGuidance).length} with authored usage guidance.`,
    "",
    parts.join("\n\n---\n\n"),
    "",
  ].join("\n");
}

const instructions = (contextPath, count) => `${START}

## UI Kit

This project uses the Pentaho UI Kit (\`@pentaho/uikit-react-core\`).

Before writing UI code, read [\`${contextPath}\`](${contextPath}). It describes all
${count} components — props, design tokens, examples, and the usage guidance and
gotchas that the type signatures do not carry.

- Build from UI Kit components rather than bare elements.
- Take colour and spacing from design tokens or utility classes, not literal values.
- Some components accept props they do not honour. The context file says which.

Regenerate after upgrading the UI Kit:

\`\`\`bash
npx uikit-cli init --agents
\`\`\`

${END}`;

/** Insert or replace our block, leaving anything the project already wrote alone. */
function upsertBlock(file, block) {
  if (!fs.existsSync(file)) {
    fs.outputFileSync(file, `${block}\n`);
    return "created";
  }
  const current = fs.readFileSync(file, "utf-8");
  if (current.includes(START) && current.includes(END)) {
    const next = current.replace(
      new RegExp(`${START}[\\s\\S]*?${END}`),
      block.trim(),
    );
    if (next === current) return "unchanged";
    fs.writeFileSync(file, next);
    return "updated";
  }
  fs.writeFileSync(file, `${current.trimEnd()}\n\n${block}\n`);
  return "appended";
}

export const initCommand = new Command()
  .name("init")
  .description("set up UI Kit support files in an existing project")
  .option(
    "-a, --agents",
    "write agent context files (AGENTS.md and the component reference)",
  )
  .option("-d, --dir <dir>", "project directory", ".")
  .action((options) => {
    if (!options.agents) {
      console.error(chalk.yellow("Nothing to do. Pass --agents."));
      process.exitCode = 1;
      return;
    }

    const index = readIndex();
    if (!index?.length) {
      console.error(
        chalk.red("No component descriptions found in this uikit-cli build."),
      );
      process.exitCode = 1;
      return;
    }

    const root = options.dir;
    if (!fs.existsSync(root)) {
      // creating the tree silently turns a typo into a stray directory
      console.error(chalk.red(`No such directory: ${root}`));
      process.exitCode = 1;
      return;
    }
    const contextPath = ".uikit/components.md";

    fs.outputFileSync(`${root}/${contextPath}`, buildContext(index));
    const outcome = upsertBlock(
      `${root}/AGENTS.md`,
      instructions(contextPath, index.length),
    );

    const bytes = fs.statSync(`${root}/${contextPath}`).size;
    console.log(
      `  ${chalk.green("✓")} ${contextPath}  ${Math.round(bytes / 1024)}KB, ~${Math.round(bytes / 4 / 1000)}k tokens`,
    );
    console.log(`  ${chalk.green("✓")} AGENTS.md  (${outcome})`);
    console.log(
      chalk.dim(
        `\n  ${index.length} components, ${index.filter((e) => e.hasGuidance).length} with usage guidance.`,
      ),
    );
    console.log(chalk.dim("  Re-run after upgrading the UI Kit."));
  });
